set_cache(UBINOS__BSP__LINK_MEMMAP_FLASH_ORIGIN 0x08000000 STRING)
set_cache(UBINOS__BSP__LINK_MEMMAP_FLASH_LENGTH 0x000E0000 STRING)

set_cache(UBINOS__BSP__LINK_MEMMAP_FLASH2_ORIGIN 0x080E0000 STRING)
set_cache(UBINOS__BSP__LINK_MEMMAP_FLASH2_LENGTH 0x00020000 STRING)

set_cache(UBINOS__BSP__LINK_MEMMAP_RAM2_ORIGIN 0x64000000 STRING)
set_cache(UBINOS__BSP__LINK_MEMMAP_RAM2_LENGTH 0x00100000 STRING)

set_cache(UBINOS__BSP__LINK_MEMMAP_TYPE "FLASH_EXTSRAM" STRING)
set_cache(UBINOS__BSP__USE_EXTSRAM TRUE BOOL)

set_cache(UBINOS__BSP__LINKSCRIPT_FILE "${PROJECT_UBINOS_DIR}/source/ubinos/bsp/arch/arm/cortexm/stm32f2x7/g/flash_extsram_aws.ld" PATH)

include(${CMAKE_CURRENT_LIST_DIR}/stm3221geval.cmake)

