#
# Copyright (c) 2019 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

# {ubinos_config_type: [buildable, cmake, app]}

set_cache(PROJECT_BUILD_TYPE "Release"   STRING)

set_cache(UBINOS__UBICLIB__EXCLUDE_CLI FALSE BOOL)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_BOUNDARY_CHECK TRUE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_INTERMEDIATE_DATA_CHECK TRUE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_LOGMD TRUE BOOL)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__FIRSTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__NEXTFIT  FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__PGROUP   FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__GROUP    FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BBUDDY   FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__WBUDDY   FALSE BOOL)

set_cache(UBINOS__UBICLIB_TEST__EXCLUDE_HEAPTEST FALSE BOOL)

include(${PROJECT_UBINOS_DIR}/config/ubinos_sam9xe512ek.cmake)
include(${PROJECT_UBINOS_DIR}/config/ubinos/ubiclib_test.cmake)

include(${PROJECT_UBINOS_DIR}/app/heap_tester.cmake)

