#
# Copyright (c) 2019 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

%:
	@echo ""
	@echo ""

ifeq ("$(SYSTEM_NAME)", "Darwin")
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : local llvm"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_local_llvm_baremetal
	@echo ""
	@echo ""
endif
ifeq ("$(SYSTEM_NAME)", "Linux")
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : local gcc"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_local_gcc_baremetal
	@echo ""
	@echo ""
endif
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_sam9xe512ek_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_sam9xe512ek_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_sam9xe512ek
	@echo ""
	@echo ""


ifeq ("$(SYSTEM_NAME)", "Darwin")
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : local llvm"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_local_llvm_baremetal
	@echo ""
	@echo ""
endif
ifeq ("$(SYSTEM_NAME)", "Linux")
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : local gcc"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_local_gcc_baremetal
	@echo ""
	@echo ""
endif
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_sam9xe512ek_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_sam9xe512ek_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_sam9xe512ek
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_sam9xe512ek
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_sam9xe512ek
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : heap tester application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=heap_tester_sam9xe512ek
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_baremetal_sram_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_softdevice_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_softdevice_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_softdevice
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52dk_softdevice_trace
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nrf52dk_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nrf52dk_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_nrf52dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nrf52dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nrf52dk
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_baremetal_sram_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_softdevice_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_softdevice_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_softdevice
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dk_softdevice_trace
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nrf52840dk_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nrf52840dk_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_nrf52840dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nrf52840dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubiclib tester application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubiclib_tester_nrf52840dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash, bidirectional heap"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nrf52840dk_bdh
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nrf52840dk
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application with bidirectional heap"
	@echo "Target board    : nrf52840dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nrf52840dk_bdh
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dongle"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dongle_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dongle"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dongle_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52840dongle"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dongle
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52840dongle"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dongle_softdevice_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52840dongle"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nrf52840dongle_softdevice
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : arduinonano33ble"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_arduinonano33ble_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : arduinonano33ble"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_arduinonano33ble_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : arduinonano33ble"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_arduinonano33ble
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : arduinonano33ble"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_arduinonano33ble_softdevice_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : arduinonano33ble"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_arduinonano33ble_softdevice
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32vldisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32vldisco_baremetal
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application on QEMU"
	@echo "Target board    : stm32vldisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32vldisco_baremetal_qemu
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : netduinoplus2"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_netduinoplus2_baremetal
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : netduinoplus2"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_netduinoplus2
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application on QEMU"
	@echo "Target board    : netduinoplus2"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_netduinoplus2_baremetal_qemu
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application on QEMU"
	@echo "Target board    : netduinoplus2"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_netduinoplus2_qemu
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application on QEMU"
	@echo "Target board    : netduinoplus2"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_netduinoplus2_qemu
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_flash_extsram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_flash_extsram_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_extsram_aws"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_flash_extsram_aws
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_extsram_aws"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_baremetal_flash_extsram_aws_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm3221geval_flash_extsram
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm3221geval_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm3221geval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm3221geval_baremetal_flash_extsram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm3221geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm3221geval_flash_extsram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm3221geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm3221geval_flash_extsram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm3221geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm3221geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash_extsram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm3221geval_flash_extsram
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleof207zg_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleof207zg_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleof207zg_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleof207zg
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleof207zg_trace
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nucleof207zg_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nucleof207zg_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_nucleof207zg
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nucleof207zg
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : nucleof207zg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nucleof207zg
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with ethernet"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_baremetal_ethernet
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library with ethernet supporting ETM trace"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_baremetal_ethernet_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769ieval_trace
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32f769ieval_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32f769ieval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32f769ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32f769ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32f769ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32f769ieval
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l475eiot01_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_aws"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l475eiot01_baremetal_aws
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l475eiot01
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32l475eiot01_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32l475eiot01
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32l475eiot01
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32l475eiot01"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32l475eiot01
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l476geval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l476geval_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l476geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32l476geval_trace
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32l476geval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32l476geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32l476geval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32l476geval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32l476geval
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleol476rg_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_nucleol476rg
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_nucleol476rg_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_nucleol476rg
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nucleol476rg
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : nucleol476rg"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nucleol476rg
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769idisco_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769idisco_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_ethernet"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769idisco_baremetal_ethernet
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash_ethernet_aws"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769idisco_baremetal_ethernet_aws
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f769idisco
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32h747idisco_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32h747idisco
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32f769idisco_baremetal_sram
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32f769idisco_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32f769idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32f769idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32f769idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32f769idisco
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32h747idisco_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32h747idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32h747idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32h747idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32h747idisco
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32429ieval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32429ieval supporting ETM trace"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32429ieval_baremetal_trace
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32429ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32429ieval_trace
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32429ieval_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32429ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32429ieval
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32429ieval"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32429ieval
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f429idisco_baremetal
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_DIR=../config CONFIG_NAME=ubinos_stm32f429idisco
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hi, World! application"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hi_world_stm32f429idisco_baremetal
	@echo ""
	@echo ""

	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : Hello, World! application"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=hello_world_stm32f429idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_stm32f429idisco
	@echo ""
	@echo ""
	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : stm32f429idisco"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_stm32f429idisco
	@echo ""
	@echo ""


	@echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	@echo ""

