###############################################################################

%:
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_sam9xe512ek_baremetal_sram            CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_sam9xe512ek_baremetal                 CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_sam9xe512ek                           CONFIG_DIR=../config
	@echo ""

	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_sam9xe512ek_baremetal_sram
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_sam9xe512ek_baremetal
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld multi-tasking application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_mt_sam9xe512ek
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubik tester application"
	@echo "Target board    : sam9xe512ek"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_sam9xe512ek
	@echo ""

	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_baremetal_sram                CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_baremetal                     CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_baremetal_trace               CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk                               CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_trace                         CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_softdevice_baremetal          CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_softdevice_baremetal_trace    CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library with softdevice"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_softdevice                    CONFIG_DIR=../config
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubinos library with softdevice supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubinos_nrf52dk_softdevice_trace              CONFIG_DIR=../config
	@echo ""

	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : sram"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_nrf52dk_baremetal_sram
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : none"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_nrf52dk_baremetal
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : helloworld multi-tasking application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=helloworld_mt_nrf52dk
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : ubik tester application supporting ETM trace"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=ubik_tester_nrf52dk
	@echo ""
	@echo "==============================================================================="	
	@echo "==============================================================================="
	@echo ""
	@echo "Config          : command line interface tester application"
	@echo "Target board    : nrf52dk"
	@echo "OS Kernel       : ubik"
	@echo "Link memory map : flash"
	@echo ""
	make -f makefile.mk $@ CONFIG_NAME=cli_tester_nrf52dk
	@echo ""


###############################################################################


