#
# Copyright (c) 2019 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_DIR ?= ../app
CONFIG_NAME ?= hello_world_netduinoplus2_qemu
# COMPILER_LAUNCHER ?= ccache

include makefile.mk


