////////


#define PROJECT_BUILD_TYPE "@PROJECT_BUILD_TYPE@"


////////


#define UBINOS__VERSION_MAJOR @UBINOS__VERSION_MAJOR@
#define UBINOS__VERSION_MINOR @UBINOS__VERSION_MINOR@
#define UBINOS__VERSION_PATCH @UBINOS__VERSION_PATCH@
#define UBINOS__VERSION_TWEAK @UBINOS__VERSION_TWEAK@
#define UBINOS__VERSION "@UBINOS__VERSION@"


////////


#cmakedefine01 INCLUDE__UBINOS__BSP

#if (INCLUDE__UBINOS__BSP == 1)

#define UBINOS__BSP__CPU_ARCH__ARM                        1
#cmakedefine UBINOS__BSP__CPU_ARCH                             UBINOS__BSP__CPU_ARCH__@UBINOS__BSP__CPU_ARCH@

#define UBINOS__BSP__CPU_TYPE__ARM926EJ_S                 2
#define UBINOS__BSP__CPU_TYPE__CORTEX_M4                  3
#cmakedefine UBINOS__BSP__CPU_TYPE                             UBINOS__BSP__CPU_TYPE__@UBINOS__BSP__CPU_TYPE@

#define UBINOS__BSP__CPU_ENDIAN__LITTLE                   1
#define UBINOS__BSP__CPU_ENDIAN__BIG                      2
#cmakedefine UBINOS__BSP__CPU_ENDIAN                           UBINOS__BSP__CPU_ENDIAN__@UBINOS__BSP__CPU_ENDIAN@

#define UBINOS__BSP__CPU_MODEL__SAM9XE512                 0x00010023
#define UBINOS__BSP__CPU_MODEL__NRF52832XXAA              0x00010311
#cmakedefine UBINOS__BSP__CPU_MODEL                            UBINOS__BSP__CPU_MODEL__@UBINOS__BSP__CPU_MODEL@

#define UBINOS__BSP__BOARD_MODEL__SAM9XE512EK             0x00020023
#define UBINOS__BSP__BOARD_MODEL__NRF52DK                 0x00020311
#cmakedefine UBINOS__BSP__BOARD_MODEL                          UBINOS__BSP__BOARD_MODEL__@UBINOS__BSP__BOARD_MODEL@

#define UBINOS__BSP__LINK_MEMMAP_TYPE__FLASH              1
#define UBINOS__BSP__LINK_MEMMAP_TYPE__SRAM               2
#define UBINOS__BSP__LINK_MEMMAP_TYPE__FLASH_SDRAM        3
#define UBINOS__BSP__LINK_MEMMAP_TYPE__SDRAM              4
#define UBINOS__BSP__LINK_MEMMAP_TYPE__EXTFLASH_SDRAM     5
#define UBINOS__BSP__LINK_MEMMAP_TYPE__SRAM_SDRAM         6
#cmakedefine UBINOS__BSP__LINK_MEMMAP_TYPE                     UBINOS__BSP__LINK_MEMMAP_TYPE__@UBINOS__BSP__LINK_MEMMAP_TYPE@

#cmakedefine01 UBINOS__BSP__USE_MMU
#cmakedefine01 UBINOS__BSP__USE_ICACHE
#cmakedefine01 UBINOS__BSP__USE_DCACHE

#cmakedefine01 UBINOS__BSP__USE_DTTY

#cmakedefine UBINOS__BSP__CLOCK_FREQ_MAIN                      @UBINOS__BSP__CLOCK_FREQ_MAIN@
#cmakedefine UBINOS__BSP__CLOCK_FREQ_SLOW                      @UBINOS__BSP__CLOCK_FREQ_SLOW@
#cmakedefine UBINOS__BSP__BUSYWAITCOUNT_PER_MS                 @UBINOS__BSP__BUSYWAITCOUNT_PER_MS@

#cmakedefine01 UBINOS__BSP__USE_EXTSDRAM
#cmakedefine01 UBINOS__BSP__USE_EXTNORFLASH

#cmakedefine UBINOS__BSP__EXTSDRAM_BUSWIDTH                    @UBINOS__BSP__EXTSDRAM_BUSWIDTH@
#cmakedefine UBINOS__BSP__EXTNORFLASH_BUSWIDTH                 @UBINOS__BSP__EXTNORFLASH_BUSWIDTH@
#cmakedefine UBINOS__BSP__EXTNORFLASH_ADDR                     @UBINOS__BSP__EXTNORFLASH_ADDR@

#cmakedefine UBINOS__BSP__STACK_SIZE                           @UBINOS__BSP__STACK_SIZE@
#cmakedefine UBINOS__BSP__STACK_OVERFLOW_CHECK_MARGIN          @UBINOS__BSP__STACK_OVERFLOW_CHECK_MARGIN@


////


#if (UBINOS__BSP__CPU_ARCH == UBINOS__BSP__CPU_ARCH__ARM)

#cmakedefine01 UBINOS__BSP__USE_RELOCATED_ISR_VECTOR

    #if (UBINOS__BSP__CPU_TYPE == UBINOS__BSP__CPU_TYPE__ARM926EJ_S)

#define UBINOS__BSP__CPU_ARMTHUMBSTATE__ARM               1
#define UBINOS__BSP__CPU_ARMTHUMBSTATE__THUMB             2
#cmakedefine UBINOS__BSP__CPU_ARMTHUMBSTATE                    UBINOS__BSP__CPU_ARMTHUMBSTATE__@UBINOS__BSP__CPU_ARMTHUMBSTATE@

#cmakedefine01 UBINOS__BSP__INCLUDE_INTERRUPT_DISABLE_ENABLE_RETRY

    #else
    #if (UBINOS__BSP__CPU_TYPE == UBINOS__BSP__CPU_TYPE__CORTEX_M4)

    #else

        #error "Unsupported UBINOS__BSP__CPU_TYPE"

    #endif
    #endif /* (UBINOS__BSP__CPU_TYPE == ...) */


    #if (UBINOS__BSP__CPU_MODEL == UBINOS__BSP__CPU_MODEL__SAM9XE512)

    #else
    #if (UBINOS__BSP__CPU_MODEL == UBINOS__BSP__CPU_MODEL__NRF52832XXAA)

#cmakedefine01 UBINOS__BSP__NRF52_NRF52
#cmakedefine01 UBINOS__BSP__NRF52_NRF52832_XXAA
#cmakedefine01 UBINOS__BSP__NRF52_NRF52_PAN_74
#cmakedefine01 UBINOS__BSP__NRF52_FLOAT_ABI_HARD

    #else

        #error "Unsupported UBINOS__BSP__CPU_MODEL"

    #endif
    #endif /* (UBINOS__BSP__CPU_MODEL == ...) */


    #if (UBINOS__BSP__BOARD_MODEL == UBINOS__BSP__BOARD_MODEL__SAM9XE512EK)

    #else
    #if (UBINOS__BSP__BOARD_MODEL == UBINOS__BSP__BOARD_MODEL__NRF52DK)

#cmakedefine01 UBINOS__BSP__NRF52_CONFIG_GPIO_AS_PINRESET
#cmakedefine01 UBINOS__BSP__NRF52_ENABLE_SWO
#cmakedefine01 UBINOS__BSP__NRF52_ENABLE_TRACE

    #else

        #error "Unsupported UBINOS__BSP__BOARD_MODEL"

    #endif
    #endif /* (UBINOS__BSP__BOARD_MODEL == ...) */

#else

    #error "Unsupported UBINOS__BSP__CPU_ARCH"

#endif /* (UBINOS__BSP__CPU_ARCH == ... */

#endif /* (INCLUDE__UBINOS__BSP == 1) */


////////


#cmakedefine01 INCLUDE__UBINOS__UBICLIB

#if (INCLUDE__UBINOS__UBICLIB == 1)

#cmakedefine01 UBINOS__UBICLIB__NOSTDLIB

#cmakedefine01 UBINOS__UBICLIB__USE_MALLOC_RETARGETING

#cmakedefine01 UBINOS__UBICLIB__USE_STDIO_RETARGETING

#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_LOGM

#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_LIST
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_DLIST
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_CIRBUF
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_BITMAP
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_MATH_EXT

#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_BOUNDARY_CHECK
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_INTERMEDIATE_DATA_CHECK
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_LOGMD
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_PRINTHEAPINFO
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BESTFIT
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__FIRSTFIT
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__NEXTFIT
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__PGROUP
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BBUDDY
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__GROUP
#cmakedefine01 UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__WBUDDY

#define UBINOS__UBICLIB__HEAP_ALGORITHM__BESTFIT                         1
#define UBINOS__UBICLIB__HEAP_ALGORITHM__FIRSTFIT                        2
#define UBINOS__UBICLIB__HEAP_ALGORITHM__NEXTFIT                         3
#define UBINOS__UBICLIB__HEAP_ALGORITHM__BBUDDY                          4
#define UBINOS__UBICLIB__HEAP_ALGORITHM__WBUDDY                          5
#define UBINOS__UBICLIB__HEAP_ALGORITHM__PGROUP                          6
#define UBINOS__UBICLIB__HEAP_ALGORITHM__GROUP                           7

#define UBINOS__UBICLIB__HEAP_LOCK_TYPE__NONE                            1
#define UBINOS__UBICLIB__HEAP_LOCK_TYPE__MUTEX                           2
#define UBINOS__UBICLIB__HEAP_LOCK_TYPE__CRITICAL                        3

#cmakedefine UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM              UBINOS__UBICLIB__HEAP_ALGORITHM__@UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE               UBINOS__UBICLIB__HEAP_LOCK_TYPE__@UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR0_M                      @UBINOS__UBICLIB__HEAP_DIR0_M@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT               @UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE          @UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE@

#cmakedefine UBINOS__UBICLIB__HEAP_DIR1_ALGORITHM              UBINOS__UBICLIB__HEAP_ALGORITHM__@UBINOS__UBICLIB__HEAP_DIR1_ALGORITHM@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR1_LOCKTYPE               UBINOS__UBICLIB__HEAP_LOCK_TYPE__@UBINOS__UBICLIB__HEAP_DIR1_LOCKTYPE@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR1_M                      @UBINOS__UBICLIB__HEAP_DIR1_M@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR1_FBLCOUNT               @UBINOS__UBICLIB__HEAP_DIR1_FBLCOUNT@
#cmakedefine UBINOS__UBICLIB__HEAP_DIR1_FBLBM_BUFSIZE          @UBINOS__UBICLIB__HEAP_DIR1_FBLBM_BUFSIZE@

#endif /* (INCLUDE__UBINOS__UBICLIB == 1) */


////////


#cmakedefine01 INCLUDE__UBINOS__UBIK

#if (INCLUDE__UBINOS__UBIK == 1)

#cmakedefine UBINOS__UBIK__TICK_PER_SEC                        @UBINOS__UBIK__TICK_PER_SEC@

#cmakedefine UBINOS__UBIK__TASK_NAME_SIZE_MAX                  @UBINOS__UBIK__TASK_NAME_SIZE_MAX@
#cmakedefine UBINOS__UBIK__TASK_PRIORITY_MAX                   @UBINOS__UBIK__TASK_PRIORITY_MAX@
#cmakedefine UBINOS__UBIK__TASK_MAXWAITSIGOBJ_MAX              @UBINOS__UBIK__TASK_MAXWAITSIGOBJ_MAX@
#cmakedefine UBINOS__UBIK__TASK_STACK_DEPTH_DEFAULT            @UBINOS__UBIK__TASK_STACK_DEPTH_DEFAULT@
#cmakedefine UBINOS__UBIK__TASK_STACK_DEPTH_MIN                @UBINOS__UBIK__TASK_STACK_DEPTH_MIN@
#cmakedefine UBINOS__UBIK__IDLETASK_STACK_DEPTH                @UBINOS__UBIK__IDLETASK_STACK_DEPTH@

#cmakedefine UBINOS__UBIK__MSGQ_MSGSIZE_MAX                    @UBINOS__UBIK__MSGQ_MSGSIZE_MAX@

#cmakedefine01 UBINOS__UBIK__EXCLUDE_TICK_HOOKFUNC

#cmakedefine01 UBINOS__UBIK__EXCLUDE_KERNEL_MONITORING
#cmakedefine01 UBINOS__UBIK__EXCLUDE_TASK_MONITORING
#cmakedefine01 UBINOS__UBIK__EXCLUDE_TASK_PRIORITY_INHERITANCE
#cmakedefine01 UBINOS__UBIK__EXCLUDE_IDLETASK_GARBAGECOLLECT
#cmakedefine01 UBINOS__UBIK__EXCLUDE_IDLETASK_HOOKFUNC
#cmakedefine01 UBINOS__UBIK__EXCLUDE_CONDV
#cmakedefine01 UBINOS__UBIK__EXCLUDE_MSGQ
#cmakedefine01 UBINOS__UBIK__EXCLUDE_SEM
#cmakedefine01 UBINOS__UBIK__EXCLUDE_SIGNAL

#cmakedefine01 UBINOS__UBIK__EXCLUDE_STIMER

#cmakedefine01 UBINOS__UBIK__EXCLUDE_HRTICK
#cmakedefine01 UBINOS__UBIK__EXCLUDE_HRTICK_TICKISR_DELAY_CHECK

#cmakedefine UBINOS__UBIK__IDLETASK_SPINWAIT_INTERVALTICK      @UBINOS__UBIK__IDLETASK_SPINWAIT_INTERVALTICK@

#endif /* (INCLUDE__UBINOS__UBIK == 1) */


////////


#cmakedefine01 INCLUDE__UBINOS__UBIK_TEST

#if (INCLUDE__UBINOS__UBIK_TEST == 1)

#cmakedefine UBINOS__UBIK_TEST__MSGBUFSIZE                     @UBINOS__UBIK_TEST__MSGBUFSIZE@
#cmakedefine UBINOS__UBIK_TEST__BUSYWAITCOUNTTESTTIMEMS        @UBINOS__UBIK_TEST__BUSYWAITCOUNTTESTTIMEMS@
#cmakedefine UBINOS__UBIK_TEST__TASKWAITTIMEMS                 @UBINOS__UBIK_TEST__TASKWAITTIMEMS@
#cmakedefine UBINOS__UBIK_TEST__TASKLOOPCOUNT                  @UBINOS__UBIK_TEST__TASKLOOPCOUNT@
#cmakedefine UBINOS__UBIK_TEST__MEMLEAK_TESTCOUNT              @UBINOS__UBIK_TEST__MEMLEAK_TESTCOUNT@
#cmakedefine UBINOS__UBIK_TEST__MEMLEAK_SIGOBJCOUNT            @UBINOS__UBIK_TEST__MEMLEAK_SIGOBJCOUNT@
#cmakedefine UBINOS__UBIK_TEST__MEMLEAK_TASKCOUNT              @UBINOS__UBIK_TEST__MEMLEAK_TASKCOUNT@
#cmakedefine UBINOS__UBIK_TEST__MSGQSIZE                       @UBINOS__UBIK_TEST__MSGQSIZE@
#cmakedefine UBINOS__UBIK_TEST__MSGQMAXCOUNT                   @UBINOS__UBIK_TEST__MSGQMAXCOUNT@

#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_MISCTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_TASKTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_TASKTESTSET2
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_TASKTESTSET3
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_SIGNALTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_MUTEXTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_SEMTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_MSGQTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_CONDVTESTSET
#cmakedefine01 UBINOS__UBIK_TEST__EXCLUDE_STIMERTESTSET

#endif /* (INCLUDE__UBINOS__UBIK_TEST == 1) */


////////


#cmakedefine01 INCLUDE__APP

#if (INCLUDE__APP == 1)

#define INCLUDE__APP__@APP__NAME@ 1

#cmakedefine APP__NAME                                 "@APP__NAME@"

#endif /* (INCLUDE__APP == 1) */


